### ISSUE TITLE
Making sure that people know about the new repository for migration metadata

### ISSUE THREAD

**Issue by kltm** [geneontology/noctua-models-migrations#1]
After a discussion with @vanaukenk , we decided to move noctua-model migration metadata from `noctua-models` to here: `noctua-models-migrations`. This is now the location for migration metadata for noctua-models, _not_ noctua-models/migrations.

I want to make sure that all the people who edit that metadata understand the change. I'll close when everybody is checked off; if I missed anybody who should know, please add them:

- [x] @kltm 
- [x] @vanaukenk 
- [x] @balhoff 
- [x] @suzialeksander 

I'll remove the metadata from noctua-models during the outage later today to help prevent confusion.

**Comment by vanaukenk** [comment]
@kltm - I added @suzialeksander to the list above since this touches on Noctua maintenance outages and it'd be good to have her know about this, too.
