### ISSUE TITLE
Write up an SOP for adding non-obsolete ontology term changes using RO as an example

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/noctua-models-migrations#7]
WIP:
https://docs.google.com/document/d/1GH-Hsd5TLcUBoXgOQKTHJpADx3VF4mCTQ9mTMuKszC8

**Comment by kltm** [comment]
@vanaukenk I took a quick look and made a couple of small suggestions.

**Comment by balhoff** [comment]
Looks good.

**Comment by kltm** [comment]
Closing, as already moved to "Done".
